services:
  quriousri-predicate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quriousri-predicate
    environment:
      - PG_HOST=${PG_HOST:-host.docker.internal}
      - PG_PORT=${PG_PORT:-5432}
      - PG_DATABASE=${PG_DATABASE:-quriousri_db}
      - PG_USER=${PG_USER:-postgres}
      - PG_PASSWORD=${PG_PASSWORD:-postgres}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    networks:
      - quriousri-network
    restart: "no"

networks:
  quriousri-network:
    driver: bridge

